resilience4j:
  circuit breaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      ratingHotelBreaker:
        baseConfig: default

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  rate limiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    circuit breakers:
      enabled: true

app:
  security:
    jwt-service-id: JWTSERVICE
